-- Supabase/PostgreSQL schema for klinik_reservasi.
-- This file intentionally contains schema only, without user/patient/demo data.
-- Run it in the Supabase SQL Editor for a clean database.

DROP TABLE IF EXISTS pembayaran CASCADE;
DROP TABLE IF EXISTS hasil_pemeriksaan CASCADE;
DROP TABLE IF EXISTS reservasi CASCADE;
DROP TABLE IF EXISTS jadwal_dokter CASCADE;
DROP TABLE IF EXISTS pasien CASCADE;
DROP TABLE IF EXISTS dokter CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id_user integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  email varchar(100),
  password varchar(255) NOT NULL,
  role varchar(20) NOT NULL CHECK (role IN ('admin','dokter','pasien','staf'))
);

CREATE TABLE dokter (
  id_dokter integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user integer NOT NULL REFERENCES users(id_user) ON DELETE CASCADE,
  nama_dokter varchar(100) NOT NULL,
  spesialisasi varchar(50)
);
CREATE INDEX dokter_id_user_idx ON dokter(id_user);

CREATE TABLE pasien (
  id_user integer NOT NULL REFERENCES users(id_user) ON DELETE CASCADE,
  nik varchar(20) PRIMARY KEY,
  nama_lengkap varchar(100) NOT NULL,
  jenis_kelamin varchar(20),
  tanggal_lahir date,
  alamat text,
  no_hp varchar(20),
  email varchar(100)
);
CREATE INDEX pasien_id_user_idx ON pasien(id_user);

CREATE TABLE jadwal_dokter (
  id_jadwal integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_dokter integer NOT NULL REFERENCES dokter(id_dokter) ON DELETE CASCADE,
  hari varchar(20) NOT NULL,
  jam_mulai time NOT NULL,
  jam_selesai time NOT NULL,
  kuota integer DEFAULT 10,
  status varchar(20) DEFAULT 'Aktif'
);
CREATE INDEX jadwal_dokter_id_dokter_idx ON jadwal_dokter(id_dokter);

CREATE TABLE reservasi (
  id_reservasi integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nik varchar(20) NOT NULL REFERENCES pasien(nik) ON DELETE CASCADE ON UPDATE CASCADE,
  id_jadwal integer NOT NULL REFERENCES jadwal_dokter(id_jadwal),
  tanggal_kunjungan date NOT NULL,
  keluhan text,
  no_antrian integer,
  status varchar(50) DEFAULT 'Menunggu',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX reservasi_id_jadwal_idx ON reservasi(id_jadwal);
CREATE INDEX reservasi_nik_idx ON reservasi(nik);

CREATE TABLE hasil_pemeriksaan (
  id_hasil integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reservasi integer NOT NULL REFERENCES reservasi(id_reservasi) ON DELETE CASCADE,
  tekanan_darah varchar(20),
  suhu_badan varchar(10),
  berat_badan varchar(20),
  diagnosa text NOT NULL,
  alergi_obat varchar(100),
  resep_obat text,
  tindakan text,
  catatan_dokter text
);
CREATE INDEX hasil_pemeriksaan_id_reservasi_idx ON hasil_pemeriksaan(id_reservasi);

CREATE TABLE pembayaran (
  id_pembayaran integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_reservasi integer NOT NULL REFERENCES reservasi(id_reservasi) ON DELETE CASCADE,
  snap_token varchar(255),
  metode_pembayaran varchar(50),
  bukti_pembayaran varchar(255),
  jumlah_bayar numeric(10,2),
  status_pembayaran varchar(20) DEFAULT 'Pending' CHECK (status_pembayaran IN ('Pending','Lunas','Gagal'))
);
CREATE INDEX pembayaran_id_reservasi_idx ON pembayaran(id_reservasi);
